#tabuada
m=int (input("Digite um numero para aparecer a tabuada"))
print ("---------------")
print(f"{m}x1={m*1}")
print (f"{m}x2={m*2}")
print(f"{m}x3={m*3}")
print(f"{m}x4={m*4}")
print(f"{m}x5={m*5}")
print(f"{m}x6={m*6}")
print(f"{m}x7={m*7}")
print(f"{m}x8={m*8}")
print(f"{m}x9={m*9}")
print(f"{m}x10={m*10}")
print("----------------")